apply plugin: "java"

version = "v1"

sourceSets.main.java.srcDirs = ["src"]

repositories{
    mavenCentral()

    ivy{
        url "https://github.com/"
        patternLayout{ artifact "/[organisation]/[module]/releases/download/[revision]/dependencies.jar" }
        metadataSources{ artifact() }
    }

    ivy{
        url "https://github.com/"
        patternLayout{ artifact "/[organisation]/[module]/releases/download/master/[revision].jar" }
        metadataSources{ artifact() }
    }

    ivy{
        url "https://github.com/"
        patternLayout{ artifact "/[organisation]/[module]/releases/download/[revision]/jabel.jar" }
        metadataSources{ artifact() }
    }
}

java{
    targetCompatibility = 8
    sourceCompatibility = JavaVersion.VERSION_1_8
}

ext{
    mindustryVersion = "v157"
}

allprojects{
    tasks.withType(JavaCompile).configureEach{
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(["--release", "8"])
    }
}

dependencies{
    compileOnly "Anuken:Mindustry:$mindustryVersion"
}

jar{
    archiveFileName = "${project.name}.jar"

    from{
        configurations.runtimeClasspath.collect{ it.isDirectory() ? it : zipTree(it) }
    }

    from(rootDir){
        include "plugin.json"
        include "market.plugin.json"
    }
}

tasks.register("syncDist", Copy){
    dependsOn jar
    from(layout.buildDirectory.file("libs/${project.name}.jar"))
    into(layout.projectDirectory.dir("dist"))
    rename { "${project.name}.jar" }
}

jar.finalizedBy(tasks.named("syncDist"))
